mesg: ttyname failed: Inappropriate ioctl for device
cassandra delete_insert_test.py::TestDeleteInsert::test_delete_insert_search false true
log_dst_dir = /root/vm_images/ZebraConf/app_meta/logs
the_test is delete_insert_test.py::TestDeleteInsert::test_delete_insert_search
rm: cannot remove '/tmp/my_log.txt': No such file or directory
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /root/dtest/bin/python
cachedir: .pytest_cache
rootdir: /root/cassandra-dtest, inifile: pytest.ini
plugins: flaky-3.7.0, timeout-1.4.2, repeat-0.9.1
timeout: 1200.0s
timeout method: signal
timeout func_only: False
collecting ... collected 1 item

delete_insert_test.py::TestDeleteInsert::test_delete_insert_search PASSED [100%]
===Flaky Test Report===

test_delete_insert_search passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

========================== 1 passed in 37.72 seconds ===========================
[msx] rc = 0
mv /tmp/my_log.txt /root/vm_images/ZebraConf/app_meta/logs/delete_insert_test.py::TestDeleteInsert::test_delete_insert_search-output_1644050005906_256412188.txt
