cassandra user_types_test.py::TestUserTypes::test_type_dropping true true
log_dts_dir = /users/masix/vm_images/ZebraConf/app_meta/logs
the_test is user_types_test.py::TestUserTypes::test_type_dropping
rm: cannot remove '/tmp/my_log.txt': No such file or directory
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /users/masix/dtest/bin/python
cachedir: .pytest_cache
rootdir: /users/masix/cassandra-dtest, inifile: pytest.ini
plugins: flaky-3.7.0, timeout-1.4.2, repeat-0.9.1
timeout: 900.0s
timeout method: signal
timeout func_only: False
collecting ... collected 1 item

user_types_test.py::TestUserTypes::test_type_dropping 
-------------------------------- live log call ---------------------------------
23:12:11,670 ccmlib.node WARNING [msx] ccmlib:node.py:start(), self.name= node1, self.pid= 19387
23:12:11,671 ccmlib.cluster WARNING [msx] ccmlib:cluster.py:start() p.pid= 19290 node.name= node1 node.pid= 19387
23:12:19,636 ccmlib.node WARNING [msx] ccmlib:node.py:start(), self.name= node2, self.pid= 19852
23:12:19,637 ccmlib.cluster WARNING [msx] ccmlib:cluster.py:start() p.pid= 19756 node.name= node2 node.pid= 19852
23:12:28,612 ccmlib.node WARNING [msx] ccmlib:node.py:start(), self.name= node3, self.pid= 20423
23:12:28,613 ccmlib.cluster WARNING [msx] ccmlib:cluster.py:start() p.pid= 20324 node.name= node3 node.pid= 20423
PASSED                                                                   [100%]
===Flaky Test Report===

test_type_dropping passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

========================== 1 passed in 48.18 seconds ===========================
[msx] rc = 0
