cassandra commitlog_test.py::TestCommitLog::test_die_failure_policy true true
log_dts_dir = /users/masix/vm_images/ZebraConf/app_meta/logs
the_test is commitlog_test.py::TestCommitLog::test_die_failure_policy
rm: cannot remove '/tmp/my_log.txt': No such file or directory
============================= test session starts ==============================
platform linux -- Python 3.6.9, pytest-3.6.4, py-1.11.0, pluggy-0.7.1 -- /users/masix/dtest/bin/python
cachedir: .pytest_cache
rootdir: /users/masix/cassandra-dtest, inifile: pytest.ini
plugins: flaky-3.7.0, timeout-1.4.2, repeat-0.9.1
timeout: 900.0s
timeout method: signal
timeout func_only: False
collecting ... collected 1 item

commitlog_test.py::TestCommitLog::test_die_failure_policy 
-------------------------------- live log call ---------------------------------
05:56:40,916 ccmlib.node WARNING [msx] ccmlib:node.py:start(), self.name= node1, self.pid= None
05:56:40,918 ccmlib.cluster WARNING [msx] ccmlib:cluster.py:start() p.pid= 7472 node.name= node1 node.pid= None
PASSED                                                                   [100%]
===Flaky Test Report===

test_die_failure_policy passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

========================== 1 passed in 20.90 seconds ===========================
[msx] rc = 0
